export type PreparedTradePlaybook = {
  id: string;
  name: string;
  direction: "LONG" | "SHORT";
  horizon: "daytrade" | "investment";
  summary: string;
  thesisTemplate: string;
  explanationTemplate: string;
  invalidationTemplate: string;
  setupTypes: string[];
  conditions: string[];
  chartPattern: string;
  sizingNotes: string;
  fundamentalFocus: string[];
  technicalFocus: string[];
  bestFor: string;
};

export const PREPARED_TRADE_PLAYBOOKS: PreparedTradePlaybook[] = [
  {
    id: "opening-drive-vwap-hold",
    name: "Opening Drive VWAP Hold",
    direction: "LONG",
    horizon: "daytrade",
    summary: "Bullish day-trade playbook for catalyst names that hold the opening drive above VWAP and keep attracting volume.",
    thesisTemplate: "Bullish day-trade thesis: the stock has a fresh catalyst, sector tailwind, and enough liquidity to keep auctioning higher as long as it stays above VWAP and the opening drive low.",
    explanationTemplate: "Execute only after the opening push holds above VWAP, buyers defend the first pullback, and volume expands on the reclaim. Treat the first consolidation as the decision zone rather than chasing the initial spike.",
    invalidationTemplate: "Exit if price loses VWAP, fails to reclaim it on the next rotation, or breaks the opening-drive low with rising sell volume.",
    setupTypes: ["Gap and Go", "Trend Resumption", "Relative Strength Leader"],
    conditions: ["VWAP Hold", "Volume Confirmation", "Higher Low"],
    chartPattern: "Channel",
    sizingNotes: "Press size only when VWAP, tape, and sector breadth stay aligned through the first pullback.",
    fundamentalFocus: ["fresh catalyst", "tight float", "sector leadership"],
    technicalFocus: ["VWAP hold", "opening-range continuation", "volume expansion"],
    bestFor: "High-volume earnings, news, or sympathy leaders in the first two hours.",
  },
  {
    id: "intraday-reclaim-rotation",
    name: "Intraday Reclaim Rotation",
    direction: "LONG",
    horizon: "daytrade",
    summary: "Bullish short-term reclaim template for stocks that flush early, stabilize, and rotate back above the level institutions actually care about.",
    thesisTemplate: "Bullish reclaim thesis: the early flush absorbed weak hands, the fundamental narrative still supports demand, and reclaiming the key intraday level should trigger a rotation back toward the prior value area.",
    explanationTemplate: "Wait for the reclaim, then take the trade only if the second test holds, momentum improves, and the bid stops backing away. The edge comes from buying regained control, not the first bounce attempt.",
    invalidationTemplate: "Exit if the reclaimed level fails, momentum stalls immediately after entry, or the next test of support is rejected on weak tape.",
    setupTypes: ["Reversal", "Failed Breakdown", "News Catalyst"],
    conditions: ["VWAP Reclaim", "Improving Momentum", "At Support"],
    chartPattern: "W Bottom",
    sizingNotes: "Risk smaller on the first reclaim and only scale after the second higher low confirms buyers stayed in control.",
    fundamentalFocus: ["still-valid catalyst", "improving sentiment", "relative resilience"],
    technicalFocus: ["level reclaim", "higher low", "momentum stabilization"],
    bestFor: "Morning shakeouts on liquid leaders that reclaim VWAP or a premarket pivot.",
  },
  {
    id: "failed-gap-fade",
    name: "Failed Gap Fade",
    direction: "SHORT",
    horizon: "daytrade",
    summary: "Bearish day-trade playbook for overhyped gaps that cannot hold the narrative once the open auctions into supply.",
    thesisTemplate: "Bearish day-trade thesis: the gap is driven more by excitement than durable sponsorship, and failure to hold the opening narrative should send price back toward prior value quickly.",
    explanationTemplate: "Short only after the opening gap fails to hold, the first bounce cannot reclaim VWAP, and sellers keep leaning on the prior support shelf. The entry is the failed reclaim, not the first flush.",
    invalidationTemplate: "Exit if price reclaims VWAP with acceptance, the failed gap zone turns into support, or squeeze volume starts overpowering the fade.",
    setupTypes: ["Gap Fill Fade", "Failed Breakout", "Relative Weakness Laggard"],
    conditions: ["At Resistance", "VWAP Reclaim", "Volume Confirmation"],
    chartPattern: "Lower High",
    sizingNotes: "Keep the stop tight above the failed reclaim and pay yourself into the first flush rather than expecting a straight trend day.",
    fundamentalFocus: ["overextended catalyst reaction", "weak sector sponsorship", "crowded long positioning"],
    technicalFocus: ["failed reclaim", "VWAP rejection", "lower-high sequence"],
    bestFor: "Overnight gap-ups that fade as soon as real volume hits the open.",
  },
  {
    id: "vwap-rejection-breakdown",
    name: "VWAP Rejection Breakdown",
    direction: "SHORT",
    horizon: "daytrade",
    summary: "Bearish intraday continuation plan for names that cannot reclaim VWAP and keep printing weak lower highs into midday liquidity.",
    thesisTemplate: "Bearish intraday thesis: sellers remain in control, the stock is lagging its group, and every reclaim attempt into VWAP is attracting supply instead of follow-through.",
    explanationTemplate: "Execute after a clean VWAP rejection or failed bounce into the intraday EMA stack. The setup is strongest when relative weakness is obvious and the stock cannot participate in market bounces.",
    invalidationTemplate: "Exit if price accepts back above VWAP, breaks the lower-high sequence, or buyers start holding higher lows through the rejection zone.",
    setupTypes: ["Breakdown", "Trend Resumption", "Relative Weakness Laggard"],
    conditions: ["Lower High", "VWAP Hold", "Volume Confirmation"],
    chartPattern: "Channel",
    sizingNotes: "Size up only after the second failed reclaim confirms the trend is orderly and not just a one-candle flush.",
    fundamentalFocus: ["weak news follow-through", "sector laggard status", "heavy overhead supply"],
    technicalFocus: ["VWAP rejection", "EMA pressure", "lower-high staircase"],
    bestFor: "Trend-down intraday names that stay weak even when the index rebounds.",
  },
  {
    id: "compounder-accumulation",
    name: "Compounder Accumulation",
    direction: "LONG",
    horizon: "investment",
    summary: "Bullish investment playbook for durable operators where quality, cash flow, and leadership justify buying a multi-quarter base.",
    thesisTemplate: "Bullish investment thesis: the business still compounds at a healthy rate, fundamentals justify a higher valuation over time, and the current base offers a patient accumulation window rather than a rushed breakout chase.",
    explanationTemplate: "Build the position around durable quality, free-cash-flow consistency, and management execution. Use technical structure only for timing entries inside the broader accumulation zone.",
    invalidationTemplate: "Exit if business quality deteriorates, the thesis on cash generation weakens materially, or the long-term base breaks with no fundamental reason to stay involved.",
    setupTypes: ["Pullback", "Base Break", "Relative Strength Leader"],
    conditions: ["Multi-Day Base", "At Support", "Volume Confirmation"],
    chartPattern: "Base",
    sizingNotes: "Scale in tranches and leave room for time; the edge is durability, not forcing a short-term timing call.",
    fundamentalFocus: ["high return on capital", "free cash flow durability", "sector leadership"],
    technicalFocus: ["base support", "constructive pullback", "volume support"],
    bestFor: "High-quality compounders resetting into weekly support or base pivots.",
  },
  {
    id: "deep-value-rerating",
    name: "Deep Value Re-rating",
    direction: "LONG",
    horizon: "investment",
    summary: "Bullish investment template for mispriced businesses where valuation support and improving internals can drive a longer re-rating cycle.",
    thesisTemplate: "Bullish investment thesis: valuation already discounts too much bad news, the balance sheet can absorb the cycle, and improving fundamentals create asymmetric upside if the market re-rates the business back toward normal multiples.",
    explanationTemplate: "Start with valuation support and balance-sheet resilience, then add exposure only if management execution and operating trends keep improving. This is a patience trade, not a momentum chase.",
    invalidationTemplate: "Exit if the value case turns into a value trap, leverage risk rises, or the expected improvement in business quality never materializes.",
    setupTypes: ["Mean Reversion", "News Catalyst", "Pullback"],
    conditions: ["At Support", "Multi-Day Base", "Relative Strength"],
    chartPattern: "Base",
    sizingNotes: "Use wider risk parameters and add only when new data confirms the market is wrong, not just early.",
    fundamentalFocus: ["valuation discount", "balance-sheet resilience", "earnings stabilization"],
    technicalFocus: ["base repair", "support holds", "relative-strength improvement"],
    bestFor: "Oversold cyclical or neglected quality names beginning a multi-month repair.",
  },
  {
    id: "broken-growth-derating",
    name: "Broken Growth De-rating",
    direction: "SHORT",
    horizon: "investment",
    summary: "Bearish investment playbook for expensive growth stories where expectations are still too high relative to the now-weaker business reality.",
    thesisTemplate: "Bearish investment thesis: the market is still pricing the company for the old growth regime, but slowing fundamentals and worsening execution point to a deeper valuation reset over time.",
    explanationTemplate: "Build the short only when the de-rating case is driven by persistent fundamental slippage, not just one bad day. Use rallies into resistance to improve entry rather than pressing weakness blindly.",
    invalidationTemplate: "Exit if growth re-accelerates, management restores confidence with real numbers, or price reclaims the long-term breakdown zone with sponsorship.",
    setupTypes: ["Breakdown", "Failed Breakout", "Relative Weakness Laggard"],
    conditions: ["At Resistance", "Lower High", "Volume Confirmation"],
    chartPattern: "Descending Triangle",
    sizingNotes: "Short smaller into fresh breakdowns and size larger only after failed rallies confirm the thesis is becoming accepted.",
    fundamentalFocus: ["slowing revenue growth", "multiple compression risk", "weak forward guidance"],
    technicalFocus: ["failed rally", "lower highs", "long-term trend break"],
    bestFor: "Former market leaders losing both narrative support and structural trend.",
  },
  {
    id: "cyclical-distribution-short",
    name: "Cyclical Distribution Short",
    direction: "SHORT",
    horizon: "investment",
    summary: "Bearish investment plan for cyclicals where macro rollover, inventory pressure, or sector deterioration creates a sustained down-cycle.",
    thesisTemplate: "Bearish investment thesis: the cycle is turning down, fundamentals are likely to deteriorate for longer than consensus expects, and distribution across the chart suggests institutions are already exiting exposure.",
    explanationTemplate: "Focus on macro sensitivity, worsening demand data, and failed rallies into prior support. The trade improves when sector peers confirm the same rollover.",
    invalidationTemplate: "Exit if the cycle bottoms sooner than expected, macro data re-accelerates, or price reclaims the distribution range with broad sector confirmation.",
    setupTypes: ["Breakdown", "News Catalyst", "Relative Weakness Laggard"],
    conditions: ["At Resistance", "Lower High", "Multi-Day Base"],
    chartPattern: "Distribution",
    sizingNotes: "Use patient entries on failed rallies and avoid oversizing the first breakdown leg if macro headlines can whip the tape.",
    fundamentalFocus: ["macro deterioration", "inventory pressure", "sector earnings rollover"],
    technicalFocus: ["distribution range", "failed bounce", "relative weakness"],
    bestFor: "Late-cycle groups where fundamentals and price both show persistent supply.",
  },
];