export type Json = string | number | boolean | null | { [key: string]: Json } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string | null;
          display_name: string | null;
          mode: "investment" | "swing" | "daytrade" | "scalp" | null;
          equity: number;
          learn_mode: boolean;
          discipline_profile: "strict" | "balanced" | "expert";
          peak_equity: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email?: string | null;
          display_name?: string | null;
          mode?: "investment" | "swing" | "daytrade" | "scalp" | null;
          equity?: number;
          learn_mode?: boolean;
          discipline_profile?: "strict" | "balanced" | "expert";
          peak_equity?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          email?: string | null;
          display_name?: string | null;
          mode?: "investment" | "swing" | "daytrade" | "scalp" | null;
          equity?: number;
          learn_mode?: boolean;
          discipline_profile?: "strict" | "balanced" | "expert";
          peak_equity?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      trades: {
        Row: {
          id: string;
          user_id: string;
          strategy_id: string | null;
          strategy_version_id: string | null;
          strategy_name: string | null;
          strategy_snapshot: Json | null;
          ticker: string;
          direction: "LONG" | "SHORT";
          asset_class: string;
          mode: "investment" | "swing" | "daytrade" | "scalp";
          setup_types: string[];
          conditions: string[];
          chart_pattern: string;
          thesis: string;
          catalyst_window: string | null;
          invalidation: string;
          scores: Json;
          notes: Json;
          f_score: number;
          t_score: number;
          f_total: number;
          t_total: number;
          conviction: "MAX" | "HIGH" | "STD" | null;
          risk_pct: number | null;
          entry_price: number | null;
          stop_loss: number | null;
          shares: number;
          tranche1_shares: number;
          tranche2_shares: number;
          tranche2_filled: boolean;
          tranche2_deadline: string | null;
          exit_t1: boolean;
          exit_t2: boolean;
          exit_t3: boolean;
          exit_price: number | null;
          r2_target: number | null;
          r4_target: number | null;
          market_price: number | null;
          source: "thesis" | "marketwatch";
          state: "initiated" | "evaluated" | "blocked" | "deployed" | "overridden" | "closed";
          classification: "in_policy" | "override" | "out_of_bounds";
          confirmed: boolean;
          closed: boolean;
          closed_at: string | null;
          closed_reason: string | null;
          journal_entry: string;
          journal_exit: string;
          journal_post: string;
          insight: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          strategy_id?: string | null;
          strategy_version_id?: string | null;
          strategy_name?: string | null;
          strategy_snapshot?: Json | null;
          ticker: string;
          direction: "LONG" | "SHORT";
          asset_class?: string;
          mode: "investment" | "swing" | "daytrade" | "scalp";
          setup_types?: string[];
          conditions?: string[];
          chart_pattern?: string;
          thesis: string;
          catalyst_window?: string | null;
          invalidation: string;
          scores?: Json;
          notes?: Json;
          f_score?: number;
          t_score?: number;
          f_total?: number;
          t_total?: number;
          conviction?: "MAX" | "HIGH" | "STD" | null;
          risk_pct?: number | null;
          entry_price?: number | null;
          stop_loss?: number | null;
          shares?: number;
          tranche1_shares?: number;
          tranche2_shares?: number;
          tranche2_filled?: boolean;
          tranche2_deadline?: string | null;
          exit_t1?: boolean;
          exit_t2?: boolean;
          exit_t3?: boolean;
          exit_price?: number | null;
          r2_target?: number | null;
          r4_target?: number | null;
          market_price?: number | null;
          source?: "thesis" | "marketwatch";
          state?: "initiated" | "evaluated" | "blocked" | "deployed" | "overridden" | "closed";
          classification?: "in_policy" | "override" | "out_of_bounds";
          confirmed?: boolean;
          closed?: boolean;
          closed_at?: string | null;
          closed_reason?: string | null;
          journal_entry?: string;
          journal_exit?: string;
          journal_post?: string;
          insight?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          strategy_id?: string | null;
          strategy_version_id?: string | null;
          strategy_name?: string | null;
          strategy_snapshot?: Json | null;
          ticker?: string;
          direction?: "LONG" | "SHORT";
          asset_class?: string;
          mode?: "investment" | "swing" | "daytrade" | "scalp";
          setup_types?: string[];
          conditions?: string[];
          chart_pattern?: string;
          thesis?: string;
          catalyst_window?: string | null;
          invalidation?: string;
          scores?: Json;
          notes?: Json;
          f_score?: number;
          t_score?: number;
          f_total?: number;
          t_total?: number;
          conviction?: "MAX" | "HIGH" | "STD" | null;
          risk_pct?: number | null;
          entry_price?: number | null;
          stop_loss?: number | null;
          shares?: number;
          tranche1_shares?: number;
          tranche2_shares?: number;
          tranche2_filled?: boolean;
          tranche2_deadline?: string | null;
          exit_t1?: boolean;
          exit_t2?: boolean;
          exit_t3?: boolean;
          exit_price?: number | null;
          r2_target?: number | null;
          r4_target?: number | null;
          market_price?: number | null;
          source?: "thesis" | "marketwatch";
          state?: "initiated" | "evaluated" | "blocked" | "deployed" | "overridden" | "closed";
          classification?: "in_policy" | "override" | "out_of_bounds";
          confirmed?: boolean;
          closed?: boolean;
          closed_at?: string | null;
          closed_reason?: string | null;
          journal_entry?: string;
          journal_exit?: string;
          journal_post?: string;
          insight?: Json | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      overrides: {
        Row: {
          id: string;
          trade_id: string;
          user_id: string;
          rules_broken: string[];
          justification: string;
          quality_flag: "valid" | "low_quality" | "high_risk";
          ai_audit: Json | null;
          timer_duration_sec: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          trade_id: string;
          user_id: string;
          rules_broken?: string[];
          justification: string;
          quality_flag?: "valid" | "low_quality" | "high_risk";
          ai_audit?: Json | null;
          timer_duration_sec?: number;
          created_at?: string;
        };
        Update: {
          rules_broken?: string[];
          justification?: string;
          quality_flag?: "valid" | "low_quality" | "high_risk";
          ai_audit?: Json | null;
        };
        Relationships: [];
      };
      discipline_metrics: {
        Row: {
          id: string;
          user_id: string;
          strategy_id: string | null;
          score: number;
          period: string;
          in_policy_count: number;
          override_count: number;
          oob_count: number;
          pnl_in_policy: number;
          pnl_override: number;
          pnl_oob: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          strategy_id?: string | null;
          score?: number;
          period: string;
          in_policy_count?: number;
          override_count?: number;
          oob_count?: number;
          pnl_in_policy?: number;
          pnl_override?: number;
          pnl_oob?: number;
          created_at?: string;
        };
        Update: {
          strategy_id?: string | null;
          score?: number;
          period?: string;
          in_policy_count?: number;
          override_count?: number;
          oob_count?: number;
          pnl_in_policy?: number;
          pnl_override?: number;
          pnl_oob?: number;
        };
        Relationships: [];
      };
      user_metrics: {
        Row: {
          id: string;
          user_id: string;
          mode: string;
          strategy_id: string | null;
          metric_id: string;
          metric_type: "fundamental" | "technical";
          name: string;
          description: string | null;
          category: string | null;
          enabled: boolean;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          mode: string;
          strategy_id?: string | null;
          metric_id: string;
          metric_type: "fundamental" | "technical";
          name: string;
          description?: string | null;
          category?: string | null;
          enabled?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          mode?: string;
          strategy_id?: string | null;
          metric_id?: string;
          metric_type?: "fundamental" | "technical";
          name?: string;
          description?: string | null;
          category?: string | null;
          enabled?: boolean;
          sort_order?: number;
        };
        Relationships: [];
      };
      watchlist_items: {
        Row: {
          id: string;
          user_id: string;
          strategy_id: string | null;
          strategy_version_id: string | null;
          strategy_name: string | null;
          strategy_snapshot: Json | null;
          ticker: string;
          direction: "LONG" | "SHORT";
          asset_class: string | null;
          mode: string;
          scores: Json | null;
          verdict: string | null;
          note: string | null;
          last_scored_at: string | null;
          flagged_at: string;
          source: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          strategy_id?: string | null;
          strategy_version_id?: string | null;
          strategy_name?: string | null;
          strategy_snapshot?: Json | null;
          ticker: string;
          direction: "LONG" | "SHORT";
          asset_class?: string | null;
          mode: string;
          scores?: Json | null;
          verdict?: string | null;
          note?: string | null;
          last_scored_at?: string | null;
          flagged_at?: string;
          source?: string | null;
        };
        Update: {
          strategy_id?: string | null;
          strategy_version_id?: string | null;
          strategy_name?: string | null;
          strategy_snapshot?: Json | null;
          ticker?: string;
          direction?: "LONG" | "SHORT";
          asset_class?: string | null;
          mode?: string;
          scores?: Json | null;
          verdict?: string | null;
          note?: string | null;
          last_scored_at?: string | null;
          source?: string | null;
        };
        Relationships: [];
      };
      user_trade_structure_items: {
        Row: {
          id: string;
          user_id: string;
          item_type: "setup_type" | "condition" | "chart_pattern";
          label: string;
          family: string;
          detail: string;
          keywords: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          item_type: "setup_type" | "condition" | "chart_pattern";
          label: string;
          family?: string;
          detail?: string;
          keywords?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          item_type?: "setup_type" | "condition" | "chart_pattern";
          label?: string;
          family?: string;
          detail?: string;
          keywords?: string[];
          updated_at?: string;
        };
        Relationships: [];
      };
      user_strategies: {
        Row: {
          id: string;
          user_id: string;
          mode: string;
          name: string;
          description: string;
          learning_goal: string | null;
          ai_instruction: string | null;
          status: "draft" | "active" | "archived";
          preset_key: string | null;
          is_preset_clone: boolean;
          is_default: boolean;
          active_version_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          mode: string;
          name: string;
          description?: string;
          learning_goal?: string | null;
          ai_instruction?: string | null;
          status?: "draft" | "active" | "archived";
          preset_key?: string | null;
          is_preset_clone?: boolean;
          is_default?: boolean;
          active_version_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          mode?: string;
          name?: string;
          description?: string;
          learning_goal?: string | null;
          ai_instruction?: string | null;
          status?: "draft" | "active" | "archived";
          preset_key?: string | null;
          is_preset_clone?: boolean;
          is_default?: boolean;
          active_version_id?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      strategy_versions: {
        Row: {
          id: string;
          strategy_id: string;
          version_number: number;
          snapshot: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          strategy_id: string;
          version_number: number;
          snapshot?: Json;
          created_at?: string;
        };
        Update: {
          version_number?: number;
          snapshot?: Json;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}